#include <stdio.h>
#include <string.h>
#include <time.h>
#include <sys/types.h>

#define STRLEN 1000

char *ptime(void) // Возвращаемое значение: ссылка на текстовую строку с текущим временем
	{
	char *tmstr;
	time_t mytime;

	mytime = time(0);

	tmstr = (char *) asctime(localtime(&mytime));
	*(tmstr + strlen(tmstr) - 1) = '\0';

	return tmstr;

	}

int main (int argc)
{
FILE *fp;
FILE *fo;
char str[STRLEN];
char *cc;

printf("Prool CMS %s\n", ptime());

if (argc!=2)
	{
	printf("usage cms gen\n");
	return 2;
	}

fp=fopen("text.txt","r");
if (fp==NULL) {printf("can't open text\n"); return 3;}

fo=fopen("body","w");
if (fp==NULL) {printf("can't open body\n"); return 3;}

while(!feof(fp))
    {
    str[0]=0;
    fgets(str,STRLEN,fp);
    cc=strchr(str,'\n'); if (cc) *cc=0;
    cc=strchr(str,'\r'); if (cc) *cc=0;
    if (str[0]==']')
	{
	if (!memcmp(str,"]title",strlen("]title"))) {fprintf(fo,"<h1>%s</h1>\n",str+strlen("]title"));}
	else if (!memcmp(str,"]date",strlen("]date"))) {fprintf(fo,"<p>Дата %s</p>\n",str+strlen("]date"));}
	else if (!memcmp(str,"]end",strlen("]end"))) {fprintf(fo,"<hr>\n");}
	}
    else
	{
	fprintf(fo,"%s\n",str);
	}
    }
fprintf(fo,"Generated by <a href=\"https://github.com/prool/proolcms\">ProolCMS</a> %s<hr>\n", ptime());
fclose(fp);
fclose(fo);
}
