#include <stdio.h>
#include <string.h>
#include <time.h>
#include <sys/types.h>

#define STRLEN 1000
#define MSG_ON_PAGE 10

char *ptime(void) // Return: string with current time
	{
	char *tmstr;
	time_t mytime;

	mytime = time(0);

	tmstr = (char *) asctime(localtime(&mytime));
	*(tmstr + strlen(tmstr) - 1) = '\0';

	return tmstr;

	}

int main (int argc)
{
FILE *fp;
FILE *fo;
FILE *f2;
char str[STRLEN];
char new_name[STRLEN];
char *cc;
int messages, messages_processed, page;
int message_counter;

printf("\nProol CMS compile at %s %s\nCurrent date     %s\n\n",__DATE__,__TIME__,ptime());

if (argc!=2)
	{
	printf("usage: cms gen\n\n");
	return 2;
	}

fp=fopen("text.txt","r");
if (fp==NULL) {printf("can't open text\n"); return 3;}

fo=fopen("index.html","w");
if (fp==NULL) {printf("can't open index.html\n"); return 3;}

// копирование header в fo (index.html)

f2=fopen("header","r");
if (f2==NULL) {printf("can't open header\n"); return 3;}
while (!feof(f2))
	{
    	str[0]=0;
    	fgets(str,STRLEN,f2);
	if (str[0]) fputs(str,fo);
	}
fclose(f2);

// первый проход: подсчет числа поцстингов
messages=0;
while(!feof(fp))
    {
    str[0]=0;
    fgets(str,STRLEN,fp);
//    cc=strchr(str,'\n'); if (cc) *cc=0;
//    cc=strchr(str,'\r'); if (cc) *cc=0;
    if (str[0]==']')
	{
	if (!memcmp(str,"]title",strlen("]title"))) messages++;
	}
    }

fclose(fp);
fp=fopen("text.txt","r");
if (fp==NULL) {printf("can't open text\n"); return 4;}

// второй проход: генерация html

messages_processed=0;
page=0;

message_counter=1;

while(!feof(fp))
    {
    str[0]=0;
    fgets(str,STRLEN,fp);
    cc=strchr(str,'\n'); if (cc) *cc=0;
    cc=strchr(str,'\r'); if (cc) *cc=0;
    if (str[0]==']')
	{
	if (!memcmp(str,"]title",strlen("]title"))) {fprintf(fo,"<h3>[%i] %s</h3>\n",message_counter++,str+strlen("]title"));}
	else if (!memcmp(str,"]date",strlen("]date"))) {fprintf(fo,"<p>Дата %s</p>\n",str+strlen("]date"));}
	else if (!memcmp(str,"]end",strlen("]end")))
		{
		fprintf(fo,"<hr>\n");
		if(++messages_processed>(MSG_ON_PAGE-1))
			{
			messages_processed=0;
			page++;
			// вывод ссылки "назад"
			fprintf(fo,"<br><a href=\"page%i.html\">&lt; Назад</a></br>\n", page);
			
			if (page==1)
				fprintf(fo,
				"<br><hr>Generated by <a href=\"https://github.com/prool/proolcms\">ProolCMS</a>, compile date %s %s <br> Generate date %s, messages %i<hr>\n",
				__DATE__, __TIME__, ptime(), messages);

			// копирование footer или footer2 в fo
			if (page==1)
				{// footer
				f2=fopen("footer","r");
				if (f2==NULL) {printf("can't open footer\n"); return 3;}
				while (!feof(f2))
					{
    					str[0]=0;
    					fgets(str,STRLEN,f2);
					if (str[0]) fputs(str,fo);
					}
				fclose(f2);
				}
			else
				{// footer2
				f2=fopen("footer2","r");
				if (f2==NULL) {printf("can't open footer2\n"); return 3;}
				while (!feof(f2))
					{
    					str[0]=0;
    					fgets(str,STRLEN,f2);
					if (str[0]) fputs(str,fo);
					}
				fclose(f2);
				}

			fclose(fo);
			sprintf(new_name,"page%i.html",page);
			fo=fopen(new_name,"w");
			if (fp==NULL) {printf("can't open page %i\n",page); return 6;}
			// копирование header2 в fo (page*)
			f2=fopen("header2","r");
			if (f2==NULL) {printf("can't open header2\n"); return 3;}
			while (!feof(f2))
				{
    				str[0]=0;
    				fgets(str,STRLEN,f2);
				if (str[0]) fputs(str,fo);
				}
			fclose(f2);
			
			fprintf(fo,"Page #%i<br>\n<hr>\n", page);

			}
		}
	}
    else
	{
	fprintf(fo,"%s\n",str);
	}
    }

if (messages>MSG_ON_PAGE)
	{// fo это page*
			// копирование footer2 в fo (page*)
			f2=fopen("footer2","r");
			if (f2==NULL) {printf("can't open footer2\n"); return 3;}
			while (!feof(f2))
				{
    				str[0]=0;
    				fgets(str,STRLEN,f2);
				if (str[0]) fputs(str,fo);
				}
			fclose(f2);
	}
else
	{// fo это index.html
			// копирование footer в fo
			f2=fopen("footer","r");
			if (f2==NULL) {printf("can't open footer\n"); return 3;}
			while (!feof(f2))
				{
    				str[0]=0;
    				fgets(str,STRLEN,f2);
				if (str[0]) fputs(str,fo);
				}
			fclose(f2);
	}
fclose(fp);
fclose(fo);
printf("messages %i\n\n", messages);
}
